apply plugin: 'org.springframework.boot'

dependencies {
	testImplementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation project(':model')
    implementation project(':usecase')
    implementation project(':dynamo-db')
    implementation project(':sqs-listener')
    implementation project(':event-publisher')
    implementation project(':reactive-web')
    
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.cloud:spring-cloud-aws-messaging:2.2.6.RELEASE'
    
    // AWS SDK
    implementation 'software.amazon.awssdk:dynamodb'
    
    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    // To disable the *-plain.jar
    enabled = false
}

bootJar {
    // Sets output jar name
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}